language: haskell
ghc:
  - '7.10'
  - 7.8
notifications:
  email: true

script:
 - cabal sandbox delete && cabal sandbox init && cabal install --only-dep --enable-tests && cabal configure --enable-tests && cabal build && cabal test