language: haskell



notifications:
  email: true

before_install:
 - cabal update
 - cabal install alex
 - cabal install happy
 - export PATH=$HOME/.cabal/bin:$PATH
 - echo $PATH
 - cabal clean
 - cabal sandbox delete || true
 - cabal sandbox init

install:
 - cabal install --only-dep --enable-tests --force-reinstalls
 - cabal configure --enable-tests

script:
 - alex --version
 - happy --version
 - cabal build
 - cabal test
