language: haskell
ghc:
  - 7.8

notifications:
  email: true

before_install:
 - cabal update
 - cabal clean
 - cabal sandbox delete || true
 - cabal sandbox init

install:
 - cabal install --only-dep --enable-tests --force-reinstalls
 - cabal configure --enable-tests

script:
 - cabal build
 - cabal test
