language: haskell
ghc:
  - '7.10'
  - 7.8
notifications:
  email: true

before_install:
 - cabal sandbox delete || true
 - cabal sandbox init

install:
 - cabal install --only-dep --enable-tests
 - cabal configure --enable-tests

script:
 - cabal build
 - cabal test