flags:
  time-locale-compat:
    old-locale: false
packages:
- '.'
extra-deps:
- HUnit-1.3.1.1
- MonadRandom-0.4.2.3
- QuickCheck-2.8.2
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- async-2.1.0
- cereal-0.4.1.1
- cereal-text-0.1.0.2
- clock-0.7.2
- fullstop-0.1.4
- generic-deriving-1.10.4.1
- hashable-1.2.4.0
- mbox-0.3.3
- mtl-2.2.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.12.1.0
- parsec-3.1.11
- primitive-0.6.1.0
- quickcheck-instances-0.3.12
- random-1.1
- random-shuffle-0.0.4
- regex-base-0.93.2
- regex-tdfa-1.2.2
- regex-tdfa-text-1.0.0.3
- safe-0.3.9
- scientific-0.3.4.6
- split-0.2.3.1
- stm-2.4.4.1
- tagged-0.8.4
- tasty-0.11.0.3
- tasty-ant-xml-1.0.2
- tasty-hunit-0.9.2
- tasty-quickcheck-0.8.4
- text-1.2.2.1
- tf-random-0.5
- time-locale-compat-0.1.1.1
- tokenize-0.3.0
- transformers-compat-0.5.1.4
- unbounded-delays-0.1.0.9
- unordered-containers-0.2.7.0
- vector-0.11.0.0
- xml-1.3.14
- zlib-0.6.1.1
resolver: ghc-8.0
