flags:
  text:
    integer-simple: false
  QuickCheck:
    base4point8: false
packages:
- '.'
extra-deps:
- MonadRandom-0.4
- QuickCheck-2.8.1
- cereal-0.4.1.1
- fullstop-0.1.4
- hashable-1.2.3.3
- mbox-0.3.1
- mtl-2.2.1
- parsec-3.1.9
- primitive-0.6
- quickcheck-instances-0.3.11
- random-1.1
- random-shuffle-0.0.4
- regex-base-0.93.2
- regex-tdfa-1.2.0
- regex-tdfa-text-1.0.0.2
- safe-0.3.9
- split-0.2.2
- text-1.2.1.1
- tf-random-0.5
- time-locale-compat-0.1.1.0
- tokenize-0.3.0
- transformers-0.4.3.0
- transformers-compat-0.4.0.4
- unordered-containers-0.2.5.1
- zlib-0.6.1.1
- HUnit-1.2.5.2
- tasty-0.10.1.2
- tasty-ant-xml-1.0.1
- tasty-hunit-0.9.2
- tasty-quickcheck-0.8.3.2
- ansi-terminal-0.6.2.1
- async-2.0.2
- generic-deriving-1.8.0
- optparse-applicative-0.11.0.2
- regex-tdfa-rc-1.1.8.3
- stm-2.4.4
- tagged-0.8.1
- unbounded-delays-0.1.0.9
- xml-1.3.14
- ansi-wl-pprint-0.6.7.2
- criterion-1.1.0.0
- Glob-0.7.5
- aeson-0.9.0.1
- cassava-0.4.3.1
- hastache-0.6.1
- mwc-random-0.13.3.2
- statistics-0.13.2.3
- vector-0.11.0.0
- vector-algorithms-0.7
- attoparsec-0.13.0.1
- blaze-builder-0.4.0.1
- dlist-0.7.1.1
- erf-2.0.0.0
- ieee754-0.7.6
- math-functions-0.1.5.2
- monad-par-0.3.4.7
- scientific-0.3.3.8
- syb-0.5.1
- vector-binary-instances-0.2.1.0
- abstract-deque-0.3
- abstract-par-0.3.3
- monad-par-extras-0.3.3
- parallel-3.2.0.6
- vector-th-unbox-0.2.1.2
resolver: ghc-7.8
